### ISSUE TITLE
Source import failed

### ISSUE THREAD

**Issue by kthoms** [digulla/org.eclipse.dash.m4e.tools#1]
I have executed the run.sh script with an Eclipse installation in the ./downloads folder.

Creating the POMs and m2_repo structure succeeded, but the script failed when running m4e-attach-sources.py. The Eclipse instance I am using has several source bundles.

---

org.eclipse.dash.m4e.tools thoms$ ./run.sh 
./m4e-import.py 0.9 (07.04.2011)
Importing plug-ins from ../downloads/eclipse-3.7 into ../downloads/eclipse-3.7_home/m2repo
Copying template...
Analysing Eclipse plugins...
Installing 882 of 882 home.m2repo.org.eclipse.xsd:org.eclipse.xsd.mapping:2.6.0 
OK
Deleting non-Eclipse artifacts...
OK
./m4e-merge.py 0.9 (13.05.2011)
./m4e-attach-sources.py 1.2 (13.05.2011)
Attaching sources in ../tmp/m2repo
Found 0 source JARs
Traceback (most recent call last):
  File "./m4e-apply-patches.py", line 26, in <module>
    from m4e.patches import PatchLoader, PatchTool
  File "/Users/thoms/git/org.eclipse.dash.m4e.tools/src/m4e/patches.py", line 22, in <module>
    from lxml import etree, objectify
ImportError: No module named lxml

**Comment by digulla** [comment]
Zitat von kthoms  
reply@reply.github.com:

> I have executed the run.sh script with an Eclipse installation in  
> the ./downloads folder.
> 
> Creating the POMs and m2_repo structure succeeded, but the script  
> failed when running m4e-attach-sources.py. The Eclipse instance I am  
> using has several source bundles.

You need to install the "lxml" module for Python. If you need  
assistance to install it, I need to know what OS you use. The short  
version is: Install it using the standard means of your OS (rpm or  
aptitude) or use pip (http://pypi.python.org/pypi/pip)

Regards,

## 

Aaron "Optimizer" Digulla a.k.a. Philmann Dark
"It's not the universe that's limited, it's our imagination.
Follow me and I'll show you something beyond the limits."
http://www.pdark.de/                   http://blog.pdark.de/
